<package format="3">
  <name>hsrb_rlp_interface_py</name>
  <version>2.0.0</version>
  <description>The hsrb_rlp_interface_py package</description>

  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>

  <license>BSD 3-clause Clear License</license>

  <author>Keisuke Takeshita</author>
  <author>Satoru Onoda</author>

  <exec_depend>rclpy</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>