#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2020 Toyota Motor Corporation

from hsrb_rlp_interface_py import robot_local_planner
from IPython.config.loader import Config
try:
    get_ipython
except NameError:
    nested = 0
    cfg = Config()
else:
    cfg = Config()
    nested = 1


from IPython.terminal.embed import InteractiveShellEmbed
shell = InteractiveShellEmbed(config=cfg,
                              banner1="RobotLocalPlanner Interactive Shell 0.0.0",
                              exit_msg="Leaving RobotLocalPlanner Interactive Shell")

LOGO = r"""
        ____  __    ____
       / __ \/ /   / __ \
      / /_/ / /   / /_/ /
     / _, _/ /__ / ____/
    /_/ /_/_____/_/
"""


with robot_local_planner.RobotLocalPlanner() as rlp:
    shell(LOGO)
