/*
Copyright (c) 2024 TOYOTA MOTOR CORPORATION
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted (subject to the limitations in the disclaimer
below) provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.
* Neither the name of the copyright holder nor the names of its contributors may be used
  to endorse or promote products derived from this software without specific
  prior written permission.
NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS
LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.
*/
/// @brief Node test that provides time optimization action for HSR-B

#include <string>
#include <tuple>

#include <gtest/gtest.h>

#include <pluginlib/class_loader.hpp>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_action/rclcpp_action.hpp>

#include <tmc_manipulation_types_bridge/manipulation_msg_convertor.hpp>
#include <tmc_planning_msgs/action/optimize_robot_trajectory.hpp>

#include "../src/optimizer_node.hpp"

namespace {

constexpr double kWaitSec = 100.0;

constexpr double kEpsilonSec = 0.01;
constexpr double kEpsilonPos = 0.0001;

// Time_from_start when optimized the orbit of GenerateSimpleGoal with default parameters
constexpr double kSimpleGoalTimeFromStart = 4.64;

moveit_msgs::msg::RobotTrajectory GenerateSimpleTrajectory() {
  // Orbit that moves 1.0 [m] forward from stationary state
  // If the robot faces the front and a stationary state, you can finish in about 4.64 seconds
  moveit_msgs::msg::RobotTrajectory robot_trajectory;
  robot_trajectory.joint_trajectory.joint_names = {"arm"};
  robot_trajectory.joint_trajectory.points.resize(2);
  robot_trajectory.joint_trajectory.points[0].positions = {0.0};
  robot_trajectory.joint_trajectory.points[0].velocities = {0.0};
  robot_trajectory.joint_trajectory.points[1].positions = {0.1};
  robot_trajectory.multi_dof_joint_trajectory.joint_names = {"odom"};
  robot_trajectory.multi_dof_joint_trajectory.points.resize(2);
  robot_trajectory.multi_dof_joint_trajectory.points[0].transforms.resize(1);
  robot_trajectory.multi_dof_joint_trajectory.points[0].transforms[0].rotation.w = 1.0;
  robot_trajectory.multi_dof_joint_trajectory.points[0].velocities.resize(1);
  robot_trajectory.multi_dof_joint_trajectory.points[1].transforms.resize(1);
  robot_trajectory.multi_dof_joint_trajectory.points[1].transforms[0].translation.x = 1.0;
  robot_trajectory.multi_dof_joint_trajectory.points[1].transforms[0].rotation.w = 1.0;
  return robot_trajectory;
}

void ValidateLastPoint(const moveit_msgs::msg::RobotTrajectory& trajectory,
                       bool do_velocity_check = true,
                       const std::string& joint_name = "arm") {
  // The goal premise generated by GenerateSimpleGoal
  // Since you will not know where you failed, use only once in one test case.
  ASSERT_EQ(1, trajectory.joint_trajectory.joint_names.size());
  EXPECT_EQ(joint_name, trajectory.joint_trajectory.joint_names[0]);

  auto last_joint_point = trajectory.joint_trajectory.points.back();
  ASSERT_EQ(1, last_joint_point.positions.size());
  EXPECT_NEAR(0.1, last_joint_point.positions[0], kEpsilonPos);

  if (do_velocity_check) {
    ASSERT_EQ(1, last_joint_point.velocities.size());
    EXPECT_NEAR(0.0, last_joint_point.velocities[0], kEpsilonPos);
  }

  ASSERT_EQ(1, trajectory.multi_dof_joint_trajectory.joint_names.size());
  EXPECT_EQ("odom", trajectory.multi_dof_joint_trajectory.joint_names[0]);

  auto last_base_point = trajectory.multi_dof_joint_trajectory.points.back();
  ASSERT_EQ(1, last_base_point.transforms.size());
  EXPECT_NEAR(1.0, last_base_point.transforms[0].translation.x, kEpsilonPos);

  if (do_velocity_check) {
    ASSERT_EQ(1, last_base_point.velocities.size());
    EXPECT_NEAR(0.0, last_base_point.velocities[0].linear.x, kEpsilonPos);
  }
}

void InitNode(rclcpp::Node::SharedPtr& node) {
  node->declare_parameter("optimize_timeout", 3.0);
  node->declare_parameter("arm.velocity", 1.0);
  node->declare_parameter("arm.acceleration", 1.0);
  node->declare_parameter("odom_x.velocity", 1.0);
  node->declare_parameter("odom_x.acceleration", 1.0);
  node->declare_parameter("odom_y.velocity", 1.0);
  node->declare_parameter("odom_y.acceleration", 1.0);
  node->declare_parameter("odom_t.velocity", 1.0);
  node->declare_parameter("odom_t.acceleration", 1.0);
}

void InitNode(rclcpp::Node::SharedPtr& server_node, rclcpp::Node::SharedPtr& client_node) {
  auto joint_state_publisher = client_node->create_publisher<sensor_msgs::msg::JointState>(
      "joint_states", rclcpp::SystemDefaultsQoS());
  auto odom_publisher = client_node->create_publisher<nav_msgs::msg::Odometry>(
      "odom", rclcpp::SystemDefaultsQoS());

  // There is no way to detect the optimization node that has received the topic, so make a proper number of times.
  for (auto i = 0; i < 20; i++) {
    sensor_msgs::msg::JointState joint_state_msg;
    joint_state_msg.name = {"base_r_drive_wheel_joint", "base_l_drive_wheel_joint", "base_roll_joint"};
    joint_state_msg.position = {0.0, 0.0, 0.0};
    joint_state_msg.velocity = {0.0, 0.0, 0.0};
    joint_state_publisher->publish(joint_state_msg);

    nav_msgs::msg::Odometry odom_msg;
    odom_msg.pose.pose.orientation.w = 1.0;
    odom_publisher->publish(odom_msg);

    rclcpp::spin_some(client_node);
    rclcpp::spin_some(server_node);
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }
}

}  // namespace

namespace hsrb_quick_path_optimizer {


// The difference in behavior due to differences in parameters and input should be performed in the node test
TEST(OptimizerNodePluginTest, Optimize) {
  pluginlib::ClassLoader<tmc_robot_local_planner::IOptimizer> loader(
      "tmc_robot_local_planner", "tmc_robot_local_planner::IOptimizer");
  auto optimizer = loader.createSharedInstance("hsrb_quick_path_optimizer/OptimizerPlugin");

  auto server_node = rclcpp::Node::make_shared("plugins");
  InitNode(server_node);

  optimizer->Initialize(server_node);

  auto client_node = rclcpp::Node::make_shared("client");
  InitNode(server_node, client_node);

  tmc_manipulation_types::TimedRobotTrajectory trajectory_in;
  tmc_manipulation_types_bridge::RobotTrajectoryMsgToTimedRobotTrajectory(
      GenerateSimpleTrajectory(), trajectory_in);

  tmc_manipulation_types::TimedRobotTrajectory trajectory_out;
  std::function<bool()> func = []() -> bool{ return false; };
  EXPECT_TRUE(optimizer->Optimize(trajectory_in, func, trajectory_out));

  std::vector<tmc_manipulation_types::TimedRobotTrajectory> trajectories_in(3, trajectory_in);
  std::vector<tmc_manipulation_types::TimedRobotTrajectory> trajectories_out;
  EXPECT_TRUE(optimizer->Optimize(trajectories_in, func, trajectories_out));
  EXPECT_EQ(trajectories_out.size(), trajectories_in.size());
}

TEST(OptimizerNodePluginTest, OptimizeMultiThread) {
  pluginlib::ClassLoader<tmc_robot_local_planner::IOptimizer> loader(
      "tmc_robot_local_planner", "tmc_robot_local_planner::IOptimizer");
  auto optimizer_single = loader.createSharedInstance("hsrb_quick_path_optimizer/OptimizerPlugin");
  auto optimizer_multi = loader.createSharedInstance("hsrb_quick_path_optimizer/OptimizerPluginMultiThread");

  auto server_node = rclcpp::Node::make_shared("plugins");
  InitNode(server_node);
  server_node->declare_parameter("thread_pool_size", 3);
  server_node->declare_parameter("acceleration_rate_for_stop", 1.0);

  optimizer_single->Initialize(server_node);
  optimizer_multi->Initialize(server_node);

  auto client_node = rclcpp::Node::make_shared("client");
  InitNode(server_node, client_node);

  tmc_manipulation_types::TimedRobotTrajectory trajectory_in;
  tmc_manipulation_types_bridge::RobotTrajectoryMsgToTimedRobotTrajectory(
      GenerateSimpleTrajectory(), trajectory_in);

  std::function<bool()> func = []() -> bool{ return false; };

  std::vector<tmc_manipulation_types::TimedRobotTrajectory> trajectories_in(100, trajectory_in);
  double duration_single;
  {
    std::vector<tmc_manipulation_types::TimedRobotTrajectory> trajectories_out;
    const auto start = std::chrono::system_clock::now();
    EXPECT_TRUE(optimizer_single->Optimize(trajectories_in, func, trajectories_out));
    const auto end = std::chrono::system_clock::now();
    EXPECT_EQ(trajectories_out.size(), trajectories_in.size() * 2);
    duration_single = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count() / 1.0e9;
  }
  double duration_multi;
  {
    std::vector<tmc_manipulation_types::TimedRobotTrajectory> trajectories_out;
    const auto start = std::chrono::system_clock::now();
    EXPECT_TRUE(optimizer_multi->Optimize(trajectories_in, func, trajectories_out));
    const auto end = std::chrono::system_clock::now();
    EXPECT_EQ(trajectories_out.size(), trajectories_in.size() * 2);
    duration_multi = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count() / 1.0e9;
  }
  // The calculation time is 3 threads, which should be about 1/3, but the test sets a safe numerical value.
  EXPECT_LT(duration_multi, duration_single * 0.67);
}

class OptimizerNodeTestBase {
 protected:
  void SetUpImpl(bool is_force_succeeded);

  void SpinSome() {
    rclcpp::spin_some(client_node_);
    rclcpp::spin_some(server_node_);
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }

  template <typename FutureT>
  void WaitForFutureComplete(const typename std::shared_future<FutureT>& future) {
    while (future.wait_for(std::chrono::microseconds(1)) == std::future_status::timeout) {
      SpinSome();
    }
  }

  moveit_msgs::msg::RobotTrajectory SendGoalSync(const moveit_msgs::msg::RobotTrajectory& trajectory, int8_t expected);
  void SendRejectedGoal(const moveit_msgs::msg::RobotTrajectory& trajectory);

  rclcpp::Node::SharedPtr client_node_;
  std::shared_ptr<OptimizerNode> server_node_;

  rclcpp_action::Client<tmc_planning_msgs::action::OptimizeRobotTrajectory>::SharedPtr client_;

  rclcpp::Publisher<sensor_msgs::msg::JointState>::SharedPtr joint_state_publisher_;
  rclcpp::Publisher<nav_msgs::msg::Odometry>::SharedPtr odom_publisher_;

  void PublishJointState(double base_roll_position = 0.0,
                         double right_wheel_velocity = 0.0,
                         double left_wheel_velocity = 0.0,
                         double base_roll_velocity = 0.0);
  void PublishOdom(double origin_to_base_yaw = 0.0);
};

void OptimizerNodeTestBase::SetUpImpl(bool is_force_succeeded) {
  rclcpp::NodeOptions options;
  options.parameter_overrides() = {
      rclcpp::Parameter("is_force_succeeded", is_force_succeeded),
      rclcpp::Parameter("arm.velocity", 1.0),
      rclcpp::Parameter("arm.acceleration", 1.0),
      rclcpp::Parameter("odom_x.velocity", 0.2),
      rclcpp::Parameter("odom_x.acceleration", 0.05),
      rclcpp::Parameter("odom_y.velocity", 0.2),
      rclcpp::Parameter("odom_y.acceleration", 0.05),
      rclcpp::Parameter("odom_t.velocity", 0.5),
      rclcpp::Parameter("odom_t.acceleration", 0.5)};
  server_node_ = std::make_shared<OptimizerNode>(options);
  server_node_->Initialize();

  client_node_ = rclcpp::Node::make_shared("client");
  client_ = rclcpp_action::create_client<tmc_planning_msgs::action::OptimizeRobotTrajectory>(
      client_node_, "optimizer/optimize");

  joint_state_publisher_ = client_node_->create_publisher<sensor_msgs::msg::JointState>(
      "joint_states", rclcpp::SystemDefaultsQoS());
  PublishJointState();

  odom_publisher_ = client_node_->create_publisher<nav_msgs::msg::Odometry>(
      "odom", rclcpp::SystemDefaultsQoS());
  PublishOdom();
}

moveit_msgs::msg::RobotTrajectory OptimizerNodeTestBase::SendGoalSync(
    const moveit_msgs::msg::RobotTrajectory& trajectory, int8_t expected) {
  tmc_planning_msgs::action::OptimizeRobotTrajectory::Goal goal;
  goal.robot_trajectory = trajectory;

  auto future_goal_handle = client_->async_send_goal(goal);
  WaitForFutureComplete(future_goal_handle);

  auto goal_handle = future_goal_handle.get();
  EXPECT_TRUE(goal_handle.get());

  auto future_result = client_->async_get_result(goal_handle);
  WaitForFutureComplete(future_result);

  auto wrapped_result = future_result.get();
  EXPECT_EQ(static_cast<int8_t>(wrapped_result.code), expected);
  EXPECT_TRUE(wrapped_result.result);
  return wrapped_result.result->robot_trajectory;
}

void OptimizerNodeTestBase::SendRejectedGoal(const moveit_msgs::msg::RobotTrajectory& trajectory) {
  tmc_planning_msgs::action::OptimizeRobotTrajectory::Goal goal;
  goal.robot_trajectory = trajectory;

  auto future_goal_handle = client_->async_send_goal(goal);
  WaitForFutureComplete(future_goal_handle);

  auto goal_handle = future_goal_handle.get();
  EXPECT_FALSE(goal_handle.get());
}

void OptimizerNodeTestBase::PublishJointState(double base_roll_position,
                                              double right_wheel_velocity,
                                              double left_wheel_velocity,
                                              double base_roll_velocity) {
  sensor_msgs::msg::JointState msg;
  msg.name = {"base_r_drive_wheel_joint", "base_l_drive_wheel_joint", "base_roll_joint"};
  msg.position = {0.0, 0.0, base_roll_position};
  msg.velocity = {right_wheel_velocity, left_wheel_velocity, base_roll_velocity};
  // There is no way to detect the optimization node that has received the topic, so make a proper number of times.
  for (auto i = 0; i < 20; i++) {
    joint_state_publisher_->publish(msg);
    SpinSome();
  }
}

void OptimizerNodeTestBase::PublishOdom(double origin_to_base_yaw) {
  nav_msgs::msg::Odometry msg;
  msg.pose.pose.orientation.z = std::sin(origin_to_base_yaw / 2.0);
  msg.pose.pose.orientation.w = std::cos(origin_to_base_yaw / 2.0);
  for (auto i = 0; i < 20; i++) {
    odom_publisher_->publish(msg);
    SpinSome();
  }
}

class OptimizerNodeTest : public ::testing::Test, public OptimizerNodeTestBase {
 protected:
  void SetUp() override { SetUpImpl(false); }
};

// Stalling, optimization of movements that move forward from the state where both the robot and the bogie are facing the front
TEST_F(OptimizerNodeTest, OptimizeSimpleTrajectory) {
  auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);
  ValidateLastPoint(result);

  // Since it should be 4.64 seconds, the ideal should be 47 points.
  ASSERT_EQ(47, result.joint_trajectory.points.size());
  EXPECT_EQ(result.multi_dof_joint_trajectory.points.size(),
            result.joint_trajectory.points.size());

  EXPECT_NEAR(kSimpleGoalTimeFromStart,
              rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds(), kEpsilonSec);
  EXPECT_NEAR(kSimpleGoalTimeFromStart,
              rclcpp::Duration(result.multi_dof_joint_trajectory.points.back().time_from_start).seconds(), kEpsilonSec);

  auto first_joint_point = result.joint_trajectory.points.front();
  EXPECT_NEAR(0.1, rclcpp::Duration(first_joint_point.time_from_start).seconds(), kEpsilonSec);
  // It is the bogie part that determines the operating time
  // What kind of acceleration the arm is depends on the optimization algorithm, so
  // Here is the fact that it does not exceed the maximum acceleration 1.0 that is working properly
  ASSERT_EQ(1, first_joint_point.positions.size());
  EXPECT_LT(0.0, first_joint_point.positions[0]);
  EXPECT_GE(0.5 * 1.0 * 0.1 * 0.1, first_joint_point.positions[0]);

  ASSERT_EQ(1, first_joint_point.velocities.size());
  EXPECT_LT(0.0, first_joint_point.velocities[0]);
  EXPECT_GE(1.0 * 0.1, first_joint_point.velocities[0]);

  auto first_base_point = result.multi_dof_joint_trajectory.points.front();
  EXPECT_NEAR(0.1, rclcpp::Duration(first_base_point.time_from_start).seconds(), kEpsilonSec);

  // Check if the bogie part has a maximum acceleration of 0.2 on the mechanism
  ASSERT_EQ(1, first_base_point.transforms.size());
  EXPECT_NEAR(0.5 * 0.2 * 0.1 * 0.1,
              first_base_point.transforms[0].translation.x, kEpsilonPos);

  ASSERT_EQ(1, first_base_point.velocities.size());
  EXPECT_NEAR(0.2 * 0.1, first_base_point.velocities[0].linear.x, kEpsilonPos);
}

// The robot turns 90 degrees and optimizes moving to the side
TEST_F(OptimizerNodeTest, RotatedOdometry) {
  PublishOdom(M_PI_2);
  auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);

  // Because it is not a test of optimization algorithm,
  // Check if you have reached the goal+just suppress that it is slower than the fastest conditions
  ValidateLastPoint(result);
  EXPECT_LT(kSimpleGoalTimeFromStart + kEpsilonSec,
            rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds());
}

// Optimization of movement from the bogie turning axis 90 degrees
TEST_F(OptimizerNodeTest, RotatedBaseRollJoint) {
  PublishJointState(M_PI_2);
  auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);

  ValidateLastPoint(result);
  EXPECT_LT(kSimpleGoalTimeFromStart + kEpsilonSec,
            rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds());
}

// Optimization of movement during trolle
TEST_F(OptimizerNodeTest, MovingBaseJoints) {
  PublishJointState(0.0, 1.0, 1.0, 1.0);
  auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);

  ValidateLastPoint(result);
  EXPECT_LT(kSimpleGoalTimeFromStart + kEpsilonSec,
            rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds());
}

// Optimization in consideration of initial speed
TEST_F(OptimizerNodeTest, InitialVelocity) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.multi_dof_joint_trajectory.points.front().velocities.front().linear.x = -0.05;

  auto result = SendGoalSync(robot_trajectory, action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);

  ValidateLastPoint(result);
  EXPECT_LT(kSimpleGoalTimeFromStart + kEpsilonSec,
            rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds());
}

// Limit speed and acceleration limit
TEST_F(OptimizerNodeTest, ChangeOptimizationRatio) {
  {
    server_node_->set_parameter(rclcpp::Parameter("velocity_ratio", 0.5));
    server_node_->set_parameter(rclcpp::Parameter("acceleration_ratio", 1.0));

    auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);
    ValidateLastPoint(result);

    // Since it should be 6.73 seconds, the ideal should be 68 points.
    ASSERT_EQ(68, result.joint_trajectory.points.size());
  }
  {
    server_node_->set_parameter(rclcpp::Parameter("velocity_ratio", 1.0));
    server_node_->set_parameter(rclcpp::Parameter("acceleration_ratio", 0.5));

    auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);
    ValidateLastPoint(result);

    // Since it should be 6.32 seconds, the ideal should be 64 points.
    ASSERT_EQ(64, result.joint_trajectory.points.size());
  }
  {
    server_node_->set_parameter(rclcpp::Parameter("velocity_ratio", 0.5));
    server_node_->set_parameter(rclcpp::Parameter("acceleration_ratio", 0.5));

    auto result = SendGoalSync(GenerateSimpleTrajectory(), action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);
    ValidateLastPoint(result);

    // It should be 7.58 seconds, so the ideal should be 76 points.
    ASSERT_EQ(76, result.joint_trajectory.points.size());
  }
}

// Use of Optimizer via the stop
TEST_F(OptimizerNodeTest, OptimizeViaStop) {
  // Optimization with initial speed in the opposite direction
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.multi_dof_joint_trajectory.points.front().velocities.front().linear.x = -0.05;

  auto result = SendGoalSync(robot_trajectory, action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);
  ValidateLastPoint(result);
  const auto duration_normal = rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds();

  server_node_->set_parameter(rclcpp::Parameter("acceleration_rate_for_stop", 2.0));

  result = SendGoalSync(robot_trajectory, action_msgs::msg::GoalStatus::STATUS_SUCCEEDED);
  ValidateLastPoint(result);
  const auto duration_via_stop = rclcpp::Duration(result.joint_trajectory.points.back().time_from_start).seconds();

  // Since the initial speed in the opposite direction, it should be in the order of initial speed zero, through full stop, and normal optimization.
  EXPECT_LT(kSimpleGoalTimeFromStart + kEpsilonSec, duration_via_stop);
  EXPECT_LT(duration_via_stop, duration_normal);
}

// Action cancellation test
TEST_F(OptimizerNodeTest, PreemptActionGoal) {
  tmc_planning_msgs::action::OptimizeRobotTrajectory::Goal goal;
  goal.robot_trajectory = GenerateSimpleTrajectory();
  for (auto i = 0; i < 100; ++i) {
    goal.robot_trajectory.joint_trajectory.points.push_back(goal.robot_trajectory.joint_trajectory.points[0]);
    goal.robot_trajectory.joint_trajectory.points.push_back(goal.robot_trajectory.joint_trajectory.points[1]);
    goal.robot_trajectory.multi_dof_joint_trajectory.points.push_back(
        goal.robot_trajectory.multi_dof_joint_trajectory.points[0]);
    goal.robot_trajectory.multi_dof_joint_trajectory.points.push_back(
        goal.robot_trajectory.multi_dof_joint_trajectory.points[1]);
  }

  auto future_goal_handle = client_->async_send_goal(goal);
  WaitForFutureComplete(future_goal_handle);

  auto goal_handle = future_goal_handle.get();
  EXPECT_TRUE(goal_handle.get());

  auto future_cancel_response = client_->async_cancel_goal(goal_handle);
  WaitForFutureComplete(future_cancel_response);

  auto future_result = client_->async_get_result(goal_handle);
  WaitForFutureComplete(future_result);

  auto wrapped_result = future_result.get();
  EXPECT_EQ(static_cast<int8_t>(wrapped_result.code), action_msgs::msg::GoalStatus::STATUS_CANCELED);
}

// The score to input is uneven
TEST_F(OptimizerNodeTest, PointsSizeMismatch) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.points.push_back(robot_trajectory.joint_trajectory.points.back());

  SendRejectedGoal(robot_trajectory);
}

// The initial speed of the joint does not exist
TEST_F(OptimizerNodeTest, NoInitialJointVelocity) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.points.front().velocities.clear();

  SendRejectedGoal(robot_trajectory);
}

// The bogie initial speed does not exist
TEST_F(OptimizerNodeTest, NoInitialBaseVelocity) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.multi_dof_joint_trajectory.points.front().velocities.clear();

  SendRejectedGoal(robot_trajectory);
}

// Unevenness of joint number and joint position
TEST_F(OptimizerNodeTest, JointPositionSizeMismatch) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.points.front().positions.push_back(0.0);

  SendRejectedGoal(robot_trajectory);
}

// Unevenness of joint number and joint speed
TEST_F(OptimizerNodeTest, JointVelocitySizeMismatch) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.points.front().velocities.push_back(0.0);

  SendRejectedGoal(robot_trajectory);
}

// Unevenness of the number of trolleyses and the number of bogies
TEST_F(OptimizerNodeTest, BasePositionSizeMismatch) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.multi_dof_joint_trajectory.points.front().transforms.push_back(
       robot_trajectory.multi_dof_joint_trajectory.points.front().transforms[0]);

  SendRejectedGoal(robot_trajectory);
}

// Unevenness of bogie joints and bogie speeds
TEST_F(OptimizerNodeTest, BaseVelocityMismatch) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.multi_dof_joint_trajectory.points.front().transforms.push_back(
       robot_trajectory.multi_dof_joint_trajectory.points.front().transforms[0]);

  SendRejectedGoal(robot_trajectory);
}

// Current position and posture only orbit
TEST_F(OptimizerNodeTest, OnePointTrajectory) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.points.pop_back();
  robot_trajectory.multi_dof_joint_trajectory.points.pop_back();

  SendRejectedGoal(robot_trajectory);
}

// Global orbital empty
TEST_F(OptimizerNodeTest, EmptyJointTrajectory) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.joint_names.clear();
  for (auto point : robot_trajectory.joint_trajectory.points) {
    point.positions.clear();
    point.velocities.clear();
  }

  SendRejectedGoal(robot_trajectory);
}

// The trolley track is empty
TEST_F(OptimizerNodeTest, EmptyBaseTrajectory) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.joint_names.clear();
  for (auto point : robot_trajectory.joint_trajectory.points) {
    point.positions.clear();
    point.velocities.clear();
  }

  SendRejectedGoal(robot_trajectory);
}

class OptimizerNodeAbortTest
    : public OptimizerNodeTestBase,
      public ::testing::TestWithParam<std::tuple<bool, int8_t>> {
 protected:
  void SetUp() override { SetUpImpl(std::get<0>(GetParam())); }
};

// Action timeout test
TEST_P(OptimizerNodeAbortTest, ActionTimeout) {
  server_node_->set_parameter(rclcpp::Parameter("optimize_timeout", 0.0));

  (void)SendGoalSync(GenerateSimpleTrajectory(), std::get<1>(GetParam()));
}

// Unauthorized joint name
TEST_P(OptimizerNodeAbortTest, InvalidJointName) {
  auto robot_trajectory = GenerateSimpleTrajectory();
  robot_trajectory.joint_trajectory.joint_names[0] = "invalid";

  (void)SendGoalSync(robot_trajectory, std::get<1>(GetParam()));
}

INSTANTIATE_TEST_SUITE_P(
    OptimizerNodeAbortTest, OptimizerNodeAbortTest,
    ::testing::Values(
        std::make_tuple(false, action_msgs::msg::GoalStatus::STATUS_ABORTED),
        std::make_tuple(true, action_msgs::msg::GoalStatus::STATUS_SUCCEEDED)));

}  // namespace hsrb_quick_path_optimizer

int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);
  rclcpp::init(argc, argv);
  return RUN_ALL_TESTS();
}
